from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class Recommendation:
    recommended_option_type: str
    title: str
    reasoning: str
    expected_units_recovered: int
    orders_protected: int
    estimated_cost: float
    tradeoff: str
    confidence: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "recommended_option_type": self.recommended_option_type,
            "title": self.title,
            "reasoning": self.reasoning,
            "expected_units_recovered": self.expected_units_recovered,
            "orders_protected": self.orders_protected,
            "estimated_cost": self.estimated_cost,
            "tradeoff": self.tradeoff,
            "confidence": self.confidence,
        }


def _option_score(option) -> float:
    """
    Score an option using only deterministic business signals.

    Higher is better.

    Priority:
    1. Recover/protect more units.
    2. Help more orders.
    3. Prefer lower cost.
    """

    if not option.feasible:
        return float("-inf")

    units = float(option.units_recovered)
    orders = float(option.orders_helped)
    cost = float(option.estimated_cost)

    score = (
        units * 10
        + orders * 25
        - cost * 0.01
    )

    return score


def recommend_response(impact, response_options) -> Recommendation:
    """
    Select the best feasible response option.

    This function does not call an LLM and does not invent
    business facts. It only evaluates the deterministic
    response options generated by response_engine.py.
    """

    feasible_options = [
        option
        for option in response_options
        if option.feasible
    ]

    if not feasible_options:
        return Recommendation(
            recommended_option_type="HUMAN_REVIEW",
            title="Escalate for human review",
            reasoning=(
                "No feasible response option was identified from "
                "the available supply-chain data."
            ),
            expected_units_recovered=0,
            orders_protected=0,
            estimated_cost=0.0,
            tradeoff=(
                "No automated recommendation can be made safely "
                "without a feasible response."
            ),
            confidence=0.0,
        )

    ranked_options = sorted(
        feasible_options,
        key=_option_score,
        reverse=True,
    )

    best = ranked_options[0]

    # Check how clearly the winner beats the second-best option.
    if len(ranked_options) == 1:
        confidence = 0.90
    else:
        best_score = _option_score(ranked_options[0])
        second_score = _option_score(ranked_options[1])

        if best_score == 0:
            confidence = 0.50
        else:
            margin = (best_score - second_score) / abs(best_score)

            if margin >= 0.30:
                confidence = 0.95
            elif margin >= 0.15:
                confidence = 0.85
            elif margin >= 0.05:
                confidence = 0.70
            else:
                confidence = 0.55

    reasoning = (
        f"{best.title} is the strongest available response because "
        f"it is feasible and is expected to recover/protect "
        f"{best.units_recovered} units across "
        f"{best.orders_helped} affected orders at an estimated "
        f"cost of ₹{best.estimated_cost:,.2f}. "
        f"Trade-off: {best.tradeoff}"
    )

    return Recommendation(
        recommended_option_type=best.option_type,
        title=best.title,
        reasoning=reasoning,
        expected_units_recovered=int(best.units_recovered),
        orders_protected=int(best.orders_helped),
        estimated_cost=float(best.estimated_cost),
        tradeoff=best.tradeoff,
        confidence=confidence,
    )


def print_recommendation(recommendation: Recommendation) -> None:
    print("\nRecommendation")
    print("-" * 50)
    print(f"Recommended action: {recommendation.title}")
    print(f"Type: {recommendation.recommended_option_type}")
    print(f"Units recovered/protected: {recommendation.expected_units_recovered}")
    print(f"Orders protected: {recommendation.orders_protected}")
    print(f"Estimated cost: ₹{recommendation.estimated_cost:,.2f}")
    print(f"Confidence: {recommendation.confidence:.0%}")
    print(f"Trade-off: {recommendation.tradeoff}")
    print(f"Reasoning: {recommendation.reasoning}")


# ---------------------------------------------------------
# Deterministic local test
# ---------------------------------------------------------

if __name__ == "__main__":
    from types import SimpleNamespace

    mock_impact = SimpleNamespace(
        total_units_at_risk=70,
        total_orders_at_risk=2,
    )

    mock_options = [
        SimpleNamespace(
            option_type="EXPEDITE",
            title="Expedite disrupted shipment",
            units_recovered=70,
            orders_helped=2,
            estimated_cost=1750,
            tradeoff="Higher cost, but restores supply quickly.",
            feasible=True,
        ),
        SimpleNamespace(
            option_type="PART_SHIP",
            title="Part-ship affected orders",
            units_recovered=0,
            orders_helped=0,
            estimated_cost=0,
            tradeoff="No immediate fulfillment benefit in this scenario.",
            feasible=False,
        ),
        SimpleNamespace(
            option_type="CUSTOMER_NOTIFY",
            title="Notify affected customers",
            units_recovered=0,
            orders_helped=2,
            estimated_cost=0,
            tradeoff="Protects customer communication but does not recover supply.",
            feasible=True,
        ),
        SimpleNamespace(
            option_type="REALLOCATE",
            title="Reallocate 70 units of X-200",
            units_recovered=70,
            orders_helped=2,
            estimated_cost=1050,
            tradeoff="Lower cost than expediting, but consumes inventory from another warehouse.",
            feasible=True,
        ),
    ]

    recommendation = recommend_response(
        mock_impact,
        mock_options,
    )

    print_recommendation(recommendation)